### ISSUE TITLE
您好，我遇到了 Error: Cannot find module 的问题

### ISSUE THREAD

**Issue by 1428245421** [iMyon/pixivPicker#12]
我下载了最新版的pixivPicker，在windows7运行时遇到了下面的报错
module.js:471
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\Personal\Desktop\ApkIDE\pixivPicker-master\app.js:
10:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
然后我排除法的在我的服务器上运行了它，系统是debian，也是同样的错误。

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'mkdirp'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/root/pixivPicker/app.js:10:14)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
root:~/pixivPicker# 

我没有能力解决这个问题，希望您有时间看一下

**Comment by Misaka13645** [comment]
`npm install` 执行了么

**Comment by 1428245421** [comment]
成功的解决了问题，太感谢您了！~
