### ISSUE TITLE
下载指定作者的全部作品 功能好像失效

### ISSUE THREAD

**Issue by Oridzuru** [iMyon/pixivPicker#13]
按照说明文件的方法执行失败了..

**Comment by iMyon** [comment]
错误信息帖一下

**Comment by Oridzuru** [comment]
D:\project\pixiv\pixivPicker\lib\getImagesArray.js:162
          env(body, function (errors, window) {
          ^

TypeError: env is not a function
    at Request._callback (D:\project\pixiv\pixivPicker\lib\getImagesArray.js:162:11)
    at Request.self.callback (D:\project\pixiv\pixivPicker\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (D:\project\pixiv\pixivPicker\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (D:\project\pixiv\pixivPicker\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)

**Comment by iMyon** [comment]
修复了报错，更新代码后执行`npm update`。
不过作者页下载这个试验功能从第一版开始就不好用，暂时也没打算重构

**Comment by Oridzuru** [comment]
已经可以使用了，感谢作者w

**Comment by Oridzuru** [comment]
目前遇到bug..
1.画师作品里遇到图册/动图，会无限卡住。

2.个别画师 会遇到这个问题  ↓↓ _(:з」∠)_

![qq 20170831094144](https://user-images.githubusercontent.com/21119100/29902501-29c8e0e8-8e31-11e7-9b7d-250adb753e95.png)
