### ISSUE TITLE
下载指定作者页面似乎失效

### ISSUE THREAD

**Issue by Misaka13645** [iMyon/pixivPicker#15]
错误信息:

读取cookie文件
获取列表中
获取列表中
/Users/xxx/pixivPicker/lib/getImagesArray.js:235
            image.user_id = $(".profile .user-name").attr("href").match(/id=(\d+)/)[1];
                                                                 ^

TypeError: Cannot read property 'match' of undefined
    at Object.done (/Users/xxx/pixivPicker/lib/getImagesArray.js:235:66)
    at process.nextTick (/Users/xxx/pixivPicker/node_modules/jsdom/lib/jsdom.js:325:18)
    at process._tickCallback (internal/process/next_tick.js:112:11)

**Comment by iMyon** [comment]
已修复
